export const ActionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  UPDATE_TO_CART: "UPDATE_TO_CART",
  DELETE_FROM_CART: "DELETE_FROM_CART",
  TOTAL_PRICE: "TOTAL_PRICE",
  OPEN_COLLAPSE: "OPEN_COLLAPSE",
  STORE_ALL: "STORE_ALL",
  SENDING_REQUEST: "SENDING_REQUEST",
  REQUEST_DATA: "REQUEST_DATA",
  REQUEST_ERROR: "REQUEST_ERROR",
  SEARCH_TABLET: "SEARCH_TABLET",
  CHARACTER_RESULTS: "CHARACTER_RESULTS",
  ADD_ORDEN: "ADD_ORDEN",
};
